### ISSUE TITLE
Create Production Git Hooks

### ISSUE THREAD

**Issue by carsongee** [mitodl/orcoursetrion#12]
Add an action to add production LMS git hooks for a given course.  We should be able to automatically determine the course type with a api call to git to each of the configured orgs and either finding one, or raising an exception.

**Comment by pdpinch** [comment]
So, you're thinking the client passes the course id and then we check all the possible orgs to find the repo? Can we have an option to just pass the correct org, or the full repo address?

**Comment by carsongee** [comment]
the org is configured: http://orcoursetrion.readthedocs.org/en/latest/api/#orcoursetrion.config.ORC_XML_ORG

**Comment by carsongee** [comment]
FYI I'm starting on this.  My plan is to add a command called `release_xml_course` and `release_studio_course` that for now, just add the production hook to the course specified on the command line, i.e. `-c 6.000001 -t Spring_2015`
