### ISSUE TITLE
Remove all git hooks

### ISSUE THREAD

**Issue by carsongee** [mitodl/orcoursetrion#13]
Add a library function and action that exercises it called `rerun_course` that removes all of our git hooks from a specified course.  The rerun_course action should either accept a switch as to whether the course is XML or  Studio for future use, or should just be two completely different actions that do the same thing until the action gets fleshed out further by additional PRs

**Comment by itsbenweeks** [comment]
I have most of this plumbing already, should you want it.

**Comment by carsongee** [comment]
gist?

**Comment by itsbenweeks** [comment]
https://gist.github.com/itsbenweeks/e1211dbeef29581e138b
