### ISSUE TITLE
Copy repo without commits

### ISSUE THREAD

**Issue by carsongee** [mitodl/orcoursetrion#14]
Add library function to copy a repository absent it's history (i.e. teams and content) to a new location.  This will plugin to the `rerun_course` xml action, and possibly the studio action as well depending on our decision to use SplitMongoModuleStore as a dependency in orcoursetrion as is currently drawn in the design doc.

**Comment by pdpinch** [comment]
Will the client need a file system to do this? Where does that leave Doof?

Does a shallow clone give you all you need? Something like:
```
git clone --depth 1 ...
git add remote rerun ...
git push rerun
```

Or can you do this all through github APIs?

**Comment by carsongee** [comment]
I haven't done full discovery yet, but I think it will be something like as above as any copy repo from github is likely to copy the history and branches.  I thought it may also work to do it the other way, copy the whole repo and then just nuke the history, but probably still some discovery work there.  Also doof will be fine for this since it will only need to be on disk for a few minutes, but I'm not sure if heroku has git installed/installable, I would think so, but haven't checked.  So that may be the doof blocker.

**Comment by carsongee** [comment]
So the code is up, and this should work with heroku still as is since they give you temp files

**Comment by carsongee** [comment]
oh and they have git 1.7 installed which I believe is the first version to support the shallow clone
