### ISSUE TITLE
Create new team on org

### ISSUE THREAD

**Issue by carsongee** [mitodl/orcoursetrion#7]
Library function and action to create a new team on a github organization.

**Comment by Ferdi** [comment]
will it include adding member to the team ?  The larger use case I have in mind:  I get the course team from stellar membership module and want to replicate it in my github course repo.

**Comment by carsongee** [comment]
Yeah, my intention is to have it look something like:

```python

def create_team(org, team_name, read_only, members):
    """Create a team in a github organization

    Args:
        org (str): Organization to create the repo in.
        team_name (str): Name of team to create.
        read_only (bool): If false, read/write, if true read_only.
        members (list): List of github usernames to add to the team.
    ...
    """
```

**Comment by carsongee** [comment]
So to do what you would ask, it would be this, and then #8 with a list you get from stellar

**Comment by carsongee** [comment]
To add architecturally/design wise. I'm intending at some point to add a `complex_actions`, or `routing` area to this project when we get far along enough to have state (i.e. database) that would compose several actions to do workflow.

**Comment by Ferdi** [comment]
you probably need to have methods for adding / removing members from repos ?  (use case : sync membership beween stellar , github & studio). Maybe a separate Courseteam class:

```python
team = Courseteam()
team.add/removeMember(); #crud
team.getfromseallar(course_id)
team.getfromgithub(org, team)

#then something like
repo.addTeam(team)
```

**Comment by carsongee** [comment]
I think I would go with that approach if I was trying to create a general purpose API for team membership, but for our use cases, I'm not even sure this is really required.  I think I would rather just have this completely replace the membership of the team. So it would be more like in the action:
```python
from pylmod.membership import Membership

def sync_team(course):
    git_hub = GitHub(....)
    pylmod = Membership(course)
    git_hub.create_team(pylmod.staff)
```
also, as a small nit, repos don't have teams in github world, but teams have repos which is a bit of weird thing to get used to.  Repositories only have "collaborators" which are individual user accounts.

**Comment by Ferdi** [comment]
I love generic apis :-)

I still think you could have made the "course" / "teams" a more central part of your apis (e.g. as a separate classes) which uses your github wrapper api (course.creategithuberpo()),   stellar api (course.getmembershpfromstaller()) etc.

**Comment by itsbenweeks** [comment]
Food for thought. There is a potential exception here if a user that is meant to be added hasn't visited the GHE server before. Their user won't exist.

**Comment by carsongee** [comment]
Yeah, quite a few exceptions to catch here @itsbenweeks. @Ferdi this is all following from the design document.  There are only 6 github calls in the doc, so having a multiple classes seems like a lot of extra overhead for not a lot of payoff.  If we end up needing more and it gets muddy in the github class, we can always subdivide then.  Long term, I think where the `Course`class will end up as a Model type class, since it is the data in the design, not the API proxy to github.  So eventually there will be a `Team` class with people in it, and a `Course` class with many instances inside it, etc.  The action router at that point would run the edx API by passing in a course properties, or the zendesk API with course properties as arguments, or the GitHub one.  For now we are generating the concept of the course at interface time, but eventually that will be application state that can be used more freely.
